
version: '3'
services:
  web:
    build: .
    volumes:
      - .:/Zeroken
       # 1. exclude volumes
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=password
    links:
      - db
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql/mysql-server:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: zeroken_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        #command: mysqld --innodb_use_native_aio=0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '43306:3306'
    tty: true

volumes:
  mysql-data:
