
version: '3'
services:
  db:
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: oilrmutp57/mysql5.7:1.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: bash -c "bundle exec foreman start "
    volumes:
      - .:/Zeroken
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local