
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
  socket:  /tmp/mysql.sock
development:
  <<: *default
  database: Preliquo_development

test:
  <<: *default
  database: Preliquo_test

production:
  <<: *default
  database: Preliquo_production
  username: preliquo
  password: <%= ENV['PRELIQUO_DATABASE_PASSWORD'] %>