name: auto_test_and_deploy
on: 
  pull_request:
    branches:
      - main
env:
  RAILS_ENV: test
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_HOST: ${DATABASE_HOST}
  MYSQL_PORT: 3306
jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checkout and install dependencie
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.7
          bundler-cache: true
      # - name: Setup Database
      #   env:
      #     MYSQL_ROOT_PASSWORD: password
      #   run: |
      #     mysql.server start
      #     gem install bundler
      #     ./bin/rails db:create
      #     ./bin/rails db:migrate
     
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: yarn
        run: yarn --frozen-lockfile

  build-test:
    name: auto build-test
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:5.6
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.7
          bundler-cache: true

      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: yarn
        run: yarn --frozen-lockfile

      - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load
      - name: run Brakeman and bundler-audit
        run: |
          bundle exec brakeman -A
          bundle exec bundler-audit
      - name: run Prettier and ESLint
        run: |
          yarn eslint-config-prettier  app/frontend/**/{*.js,*.vue}
          yarn prettier --check app/frontend
          yarn eslint  --max-warnings=0 app/frontend/**/{*.js,*.vue}
      # Run Linter
      - name: Run Rubocop
        run: |
          bundle exec rubocop --parallel
      # Run RSpec (added later)

  # deploy:
  #   name: auto deploy to heroku
  #   needs: [prepare, build-test]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #         heroku_email: ${{secrets.HEROKU_EMAIL}}
  #         # TODO: add a route for health check
  #         healthcheck: "https://preliquo.herokuapp.com" 